### ISSUE TITLE
Background Color

### ISSUE THREAD

**Issue by MattW86** [nacho4d/ClockView#4]
Hello,
How can I change the background color?  something like clockView1.backgroundColor = [UIColor blackColor] didn't work for me.

Thanks..

**Comment by josepharthur** [comment]
How can we change the background graphic? as a texture or an image?

**Comment by nacho4d** [comment]
Sorry for the late response.  You can change the background by providing an image:

    [clockView setClockBackgroundImage:[UIImage imageNamed:@"clock-background"].CGImage];

This image will be drawn in a layer which will become the first child of the clock itself. This layer covers the entirely. So unless the image has transparency doing the following has no much sense since the clock view itself is it covered and its background is not visible:

    clockView1.backgroundColor = [UIColor blackColor];


For further examples please refer the README.markdown

**Comment by nacho4d** [comment]
I am closing this issue since above explanation will solve this. :)
Feel free to reopen again if needed
